### ISSUE TITLE
ref_tes' is not defined

### ISSUE THREAD

**Issue by Tcvalenzuela** [GonzalezLab/MCHelper#1]
Hi

Thank for this effort, I'm trying to annotate a TE library that I got from several TE de-novo pipelines

Here my line
python Programs/MCHelper/MCHelper.py \
-r E \
 -g $Reference_genome \
-o $Out_working_directory
-l $Database   #of TE in_multifasta_format \
-t 2

and I get the error:

Traceback (most recent call last):
  File "Programs/MCHelper/MCHelper.py", line 2935, in <module>
    run_extension_by_saturation_parallel(genome, ref_tes, ext_nucl, num_ite,
NameError: name 'ref_tes' is not defined

What I'm missing?

**Comment by simonorozcoarias** [comment]
Hi,

It seemed to be a problem with an unused variable within the code. I just corrected it. So, please download again the MCHelper.py file and try again.

Thank you for using MCHelper !!!

**Comment by Tcvalenzuela** [comment]
Thanks for the quick response.
The fresh installation generate a new error 

Same parameters

#########################################################################
                                                                       #
                             MCHelper                                  #
   Instructions:  Execute the program, press q to close the graph and  #
     press a number 2-42 if you want to keep the TE, or 1 otherwise.   #
                                                                       #
#########################################################################

MESSAGE: Missing -s parameter, using by default: 60
MESSAGE: Missing -e parameter, using by default: 500
MESSAGE: Missing -x parameter, using by default: 16
MESSAGE: Starting with BEE step ...
Traceback (most recent call last):
  File "Programs/MCHelper/MCHelper.py", line 2935, in <module>
    run_extension_by_saturation_parallel(genome, user_library, ext_nucl, num_ite,
  File "Programs/MCHelper/MCHelper.py", line 1670, in run_extension_by_saturation_parallel
    "cons_size": [len(tes[i].seq)], "class": str(tes[i].id).split("#")[1], "subfamilies": 0, "end_l": False,
IndexError: list index out of range

**Comment by simonorozcoarias** [comment]
Have your sequence IDs the character "#" to separate the classification to the ID of the model?

**Comment by Tcvalenzuela** [comment]
No I was expecting to get the classification from MCHelper, the header of the TE database is just a number as: 
#>seq_1
#ATCG
#>seq_2
#ATCG

Does it should say something like :

#>seq_1#Unknown  ?

**Comment by simonorozcoarias** [comment]
Yes, your sequences IDs must have #Unknow or #Unclassified. If you want to get a classification from MCHelper, so you need to use the '-r U'. Let's see the following example: 

python3 MCHelper.py -r U -g genome.fna -o output_path -l TE_lib.fa -t 4 -m reference_lib.fa -b busco_genes_odb10.hmm

For the reference TE library (used in -m parameter) I suggest to use a manually curated TE library of your species of interest (or something close). For the -b parameter, I recommend to use the BUSCO genes and they must be in HMM format (all marged in one single file).  

Best wishes!
