### ISSUE TITLE
ReadMe Installation Errors.

### ISSUE THREAD

**Issue by Jakeelamb** [GonzalezLab/MCHelper#3]
The instructions for the installation are wrong due to unintended capitalizations in the paths. I fixed this with a fork and pull request but was ignored. The git clone command saves the directory as mchelper , yet the following commands reference a capitalized MCHelper directory. 

conda env create -f MCHelper/MCHelper.yml
cd MCHelper/db

These should be changed to:
conda env create -f mchelper/MCHelper.yml
cd mchelper/db

or the repository should be changed to MCHelper from mchelper

Thanks for the awesome tool! Great work :)

**Comment by simonorozcoarias** [comment]
Hi ! 

Thank you for using MCHelper !!! Which SO, git version and command line have you used to clone the MCHelper repo? I have tried in several OS (Ubuntu 22.04, Rocky 8.5, MacOS 10.12, Windows 10 through WSL) and always the cloned folder is "MCHelper". 

Best regards!
