### ISSUE TITLE
makeblastdb

### ISSUE THREAD

**Issue by rissidaniel** [GonzalezLab/MCHelper#6]
Hello,
Please I have a problem when setting the database in the "makeblastdb -in allDatabases.clustered_rename.fa -dbtype nucl" step:

Could you please help me fix it?

The error:

Building a new DB, current time: 02/08/2024 15:59:14
New DB name:   /mnt/beegfs/mnt/work/bioinfo/home/dar21/MCHelper/db/allDatabases.clustered_rename.fa
New DB title:  allDatabases.clustered_rename.fa
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /mnt/beegfs/mnt/work/bioinfo/home/dar21/MCHelper/db/allDatabases.clustered_rename.fa
Keep MBits: T
Maximum file size: 1000000000B
Bus error (core dumped)

**Comment by simonorozcoarias** [comment]
Hi @rissidaniel,

Sorry for the very late reply. That error is produced by blast, so, I don't have many clues. Maybe it is because a disk/memory issue with your own PC? 

Best,
