### ISSUE TITLE
Depreciation flags

### ISSUE THREAD

**Issue by Jakeelamb** [GonzalezLab/MCHelper#7]
There appears to be a depreciation of function within the code. When running, this is thrown repeatedly although the code still appears to run.

bin/MCHelper/MCHelper.py:1661: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  fasta_table_ite = pd.concat([fasta_table_ite, pd.DataFrame({"seq": name, "cons": s, "cons_size": [len(s)], "class": te_class, "subfamilies": [num_subfamilies], "end_l": end_l_te, "end_r":  end_r_te})], ignore_index=True)
bin/MCHelper/MCHelper.py:1875: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  fasta_table_ite = pd.concat([fasta_table_ite, pd.DataFrame({"seq": fasta_table.loc[index, "seq"], "cons": fasta_table.loc[index, "cons"], "cons_size": [fasta_table.loc[index, "cons_size"]], "class": fasta_table.loc[index, "class"], "subfamilies": fasta_table.loc[index, "subfamilies"], "end_l": True, "end_r": True})], axis=0, ignore_index=True)

**Comment by simonorozcoarias** [comment]
Hi @JakeG0at,

Thank you for using MCHelper. Yes, we are aware of this and will replace outdated instructions in future releases. Although these messages are very annoying (sorry), we have not received any reports of them affecting MCHelper results. So, for now, please ignore them and we will work to remove those disturbing messages in the next release.

Best!

**Comment by simonorozcoarias** [comment]
This issue is already solved in the last release 1.7.0.

Best,

Simon.
