### ISSUE TITLE
Classification module without BEE

### ISSUE THREAD

**Issue by ting-hsuan-chen** [GonzalezLab/MCHelper#9]
Hi,

Thank you for developing MCHelper. I would like to run just the classification module of MCHelper with the option `--module=U`. However it seems that this module also contains BEE step. Is it possible to disable the BEE step in the classification module? E.g. using the parameters `-e 1 -x 0`?

Kind regards,
Ting-Hsuan

**Comment by simonorozcoarias** [comment]
Hi !!

Thank you for using MCHelper. Yes, you can disable the BEE module setting the number of iteration to zero (-x 0).

Best,

Simon.

**Comment by ting-hsuan-chen** [comment]
Got it! Thank you!
